# SPDX-FileCopyrightText: 2020 Gabriel Lisaca <gabriel.lisaca@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ['setuptools', 'wheel', 'jinja2>=2.10,<3']

[tool.black]
line-length = 79
target-version = ['py37']
